version: '3'
services:
    web:
        build:
            context: Backend
            dockerfile: nginx.Dockerfile
        image: nginx
        ports:
            - "8888:80"
        depends_on:
            - php
        restart: always
    frontend:
        image: vaibhavgawad/codechef-frontend:latest
        ports:
            - "8081:80"
    php:
        build:
            context: Backend
            dockerfile: dev.Dockerfile
        depends_on:
            - mysql
        restart: always
    mysql:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'vaibhav'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'slimphp'
        volumes:
            - slimphp:/var/lib/mysql
        ports:
            - "3325:3306"
        restart: always
    
volumes:
   slimphp: 