version: '3'
services:
    web:
        build:
            context: Backend
            dockerfile: nginx.Dockerfile
        image: nginx
        ports:
            - "8888:80"
        volumes:
            - ./Backend/app:/app
        depends_on:
            - php
        restart: always
    frontend:
        build:
            context: FrontEnd
            dockerfile: Dockerfile
        image: nginx-frontend
        ports:
            - "8081:80"
    php:
        build:
            context: Backend
            dockerfile: dev.Dockerfile
        volumes:
            - ./Backend/app:/app:vaibhav
        depends_on:
            - mysql
        restart: always
    mysql:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'vaibhav'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'slimphp'
        volumes:
            - slimphp:/var/lib/mysql
        ports:
            - "3325:3306"
        restart: always
    
volumes:
   slimphp: {}