version: '3'
services:
    web:
        image: nginx:1.25.2-alpine3.18
        ports:
           - "8080:80"
        volumes:
            - ./Backend/conf.d:/etc/nginx/conf.d
            - ./Backend/app:/app
        depends_on:
            - php
        restart: always
    php:
        build:
            context: ./Backend
            dockerfile: PHP.Dockerfile
        volumes:
            - ./Backend/app:/app  # Corrected volume syntax
        depends_on:
            - mysql
        restart: always
    mysql:
        image: mariadb:11.1.2-jammy
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'vaibhav'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'slimphp'
        volumes:
            - slimphp:/var/lib/mysql  # Corrected volume syntax
        ports:
            - "3325:3306"
        restart: always

volumes:
   slimphp: